---
- name: "install dependencies"
  become: yes
  apt:
    name: ["build-essential"]
    state: latest
    update_cache: yes

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Extract Backend
  unarchive:
    src: "artifact.tar.gz"
    dest: "~/web"

- name: Launch backend
  shell: |
    env 
    cd ~/web/dist
    pm2 stop default
    pm2 start npm -- start